# By default types specified in commitizen/conventional-commit-types is used.
# See: https://github.com/commitizen/conventional-commit-types/blob/v2.3.0/index.json
# You can override the valid types
types:
  - feat
  - fix
  - improvement
  - docs
  - refactor
  - test
  - ci
  - chore
  - skip changelog
  - skip ci
