awsRegion: us-west-2

rbac:
  create: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::<ACCOUNT ID>:role/cluster-autoscaler"

autoDiscovery:
  clusterName: test-eks-irsa
  enabled: true
