name: CHANGELOG Checks
on:
  pull_request_target:
    paths:
      - CHANGELOG.md
    branches-ignore:
      - releases/**

jobs:
  comment:
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - name: Find Existing PR Comment
        id: prc
        uses: peter-evans/find-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "The `CHANGELOG.md` file contents are handled by the maintainers during merge."
      - name: PR Comment
        if: ${{ steps.prc.outputs.comment-id == '' }}
        uses: peter-evans/create-or-update-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thank you for your contribution!

            The `CHANGELOG.md` file contents are handled by the maintainers during merge. This is to prevent pull request merge conflicts.
            Please see the Contributing Guide for additional pull request review items.

            Remove any changes to the `CHANGELOG.md` file and commit them in this pull request.
      - name: Fail the check if changelog change
        run: exit 1
